set windows-shell := ["C:/Program Files/Git/bin/bash.exe", "-c"]

# Default recipe (shows help)
default:
    @just --list

# Show help
help:
    @just --list

# Clean autogenerated files
clean:
    rm -rf dist
    find . -type f -name "*.DS_Store" -ls -delete
    find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
    find . | grep -E ".pytest_cache" | xargs rm -rf
    find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
    rm -f .coverage

# Setup the environment
setup:
    uv venv
    uv sync --all-extras
    uv run pre-commit install

# Run pre-commit hooks
format:
    uv run pre-commit run -a

# Run pytest
test:
    uv run pytest -v --cov

# Run pyright
type:
    uv run pyright

# Run all workflow (format, test, type)
run: format test type

# Run a manual end-to-end scenario script (e.g. `just manual launch_terminate`)
manual NAME:
    uv run python tests/manual/{{NAME}}.py
